functional:
  - Представить возможность двум игрокам соревноваться друг с другом в решении задач и видеть написание кода друг у друга
  - Должны быть рейтинги
  - У пользователя должна быть возможность создать игру с другом по ссылке (соответственно второй пользователь должен иметь возможность принять приглашение по ссылке)
  - У пользователя должна быть возможность создать игру с ботом
  - Пользователь должен авторизоваться
  - При подключении двоих игроков должно перекинуть в игру 
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Игрок не может редактировать код противника
